subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm

obj-$(CONFIG_BATTERY_SEMC_ARCH) += semc_battery_data.o
obj-$(CONFIG_SEMC_CHARGER_USB_ARCH) += semc_charger_usb.o
obj-$(CONFIG_SEMC_RPC_SERVER_HANDSET) += semc_rpc_server_handset.o
