subdir-ccflags-$(CONFIG_ARCH_MSM) += -Iarch/arm/mach-msm

-include $(src)/Makefile.board

obj-$(CONFIG_MSM_HUAWEI_HWPROPS) += huawei_hwprops.o
obj-$(CONFIG_MSM_HUAWEI_RMT_OEMINFO) += huawei_rmt_oeminfo.o
